name: neurodrive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  intl: ^0.20.2
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0
  flutter_local_notifications: ^16.2.0
  fl_chart: ^0.66.0
  flutter_riverpod: ^3.0.0
  provider: ^6.1.5+1
  geolocator: ^14.0.2
  firebase_messaging: ^16.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
